### ISSUE TITLE
Second path param in a PUT is mistakenly substituted with request body

### ISSUE THREAD

**Issue by peisenmann** [CareLogistics/somni#16]
Given a route

``` clojure
  {:uri "codes/:code/:entry",
    :put #'codetable/update-codetable-entry}
```

and a function

``` clojure
(defn update-codetable-entry
  "Update the attributes of a codetable"
  [catalog-conn code entry codetable]
  (clojure.pprint/pprint [code entry codetable]))
```

My expectation is that `code` will be the first path param, `:code`. `entry` will be the second path param, `:entry`, and `codetable` will contain the body of the request.

Attempting to hit the service with an `application/json` request to  `/codes/foo/bar` with request body

``` json
{
        "ordinal": 1,
        "name": "Foo",
        "value": "Bar"
}
```

incorrectly prints to the console

``` clojure
["foo" 
 {:ordinal 1,
  :name "Foo",
  :value "Bar"}
 {:ordinal 1,
  :name "Foo",
  :value "Bar"}]
```

Here we can see the second path parameter, which should have been `"bar"` was incorrectly sent as the request body.

Attempting to hit the service with an `application/json` request to  `/codes/foo/bar` with request body

``` json
{
        "codetable": {
            "ordinal": 1,
            "name": "Foo",
            "value": "Bar"
        }
}
```

correctly prints to the console

``` clojure
["foo" 
 "bar"
 {:ordinal 1,
  :name "Foo",
  :value "Bar"}]
```

Here we can see that with no code changes other than adding to the body of the request a layer of indirection to match the internal server variable names, it works as expected. However, the extra mapping should not be required when there is no ambiguity in the intent of the client or the application.

**Comment by agarman** [comment]
Closed by #17
